apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "plugin-repo"
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "plugin-repo"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "plugin-repo"
subjects:
- kind: ServiceAccount
  name:  plugin-repo
  namespace: REPLACE_WITH_TARGET_NAMESPACE
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name:  plugin-repo
imagePullSecrets:
- name: pull-secret-ua
---
apiVersion: v1
kind: Secret
metadata:
  name: plugin-repo-https-secret
  labels: 
    app: "plugin-repo"
    heritage: "Tiller"
    release: "full-scorpion"
type:  Opaque 
data:
  localhost.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNvekNDQVlzQ0ZHN0VNTXVRbkJiM01IOTN2RkdjbnZjb2dpZTVNQTBHQ1NxR1NJYjNEUUVCQ3dVQU1BNHgKRERBS0JnTlZCQXNNQTBsQ1RUQWVGdzB5TkRBMU1qY3hNakV4TXpsYUZ3MHlOVEExTWpjeE1qRXhNemxhTUE0eApEREFLQmdOVkJBc01BMGxDVFRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTUIrCkp5SUI0YjIrd0ZDQjNmMVZKbm90UWMvTUpFclVZNm1qMUJkK1dWa3d0dFFGM0hMdGJPMzIyaGtTSllpY0ppYksKK2ovUTZoUjhvcXgvdGxRSG1lak54OGt4RzdLdDU2aXhSMTdvYkRuYjlRNWJ2Y3VtTnJUdjJkUEhrbExwZDZqVQo1bXl4ekd2SkhvNUZFNjFZWFVEMVd2eUpQN1hPS1lVT0ZFdmg4M29sVkRBVmpKK1FkbkE5UFYzalFpR2JwRWgvCmN2WTJWRWdQTkczazFIRDRTRkVmd1MrTWN0aFErWWdSM0lvNnZES2s3cE9pSk5rekNMNEMwQVBGVDAwN3NjdnQKRGFZczcwOEsyVjBKZTk5L1dnQjlLeEVyNklJaWxhZ1dleUtOa3FyWWpkYUtjcWhXbStCTnBqWWk4VWxBNDNDNgovT1ZkQjRyUTgvcDVQRWpHRmU4Q0F3RUFBVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBZVFqL3pSVkdCY1JZCjhCK3JPdHFlSktkZmd2cC9PSVdaQXhkcFlxbGttL3l5aExKWjFLTlJyeWRiYnFvaGhqdHI4VzJmL0F3TS9uNzkKWXltVE1OaXZVTEwzMElwMGdqdDF2NDdyRnhtU2tqRWFkazBXaVgzYzAyS2JMN2MzMFZyT1JaTXpmb0ZwSnBLVgpzS3NyK3pMcitOOWJQN3ZqZDBrR2FPdDc2SXBPUEt6cW1UM2duZ2o2bHBPcmZaLzhjbTk1Q2RHRWMvbE9CdTY4ClZUVXlodjhTUldVQ045RitjWGtyWDUxNUdHU0RQZUxRdS9ERUg4MDRaRG51TzcxSnVkaXNSSHJtL2Z2NUdBYkQKNld6SnRyeUF4UlRkek9jOStoOGtLUzI3WVNhS3dYM0dYbEtiTDVUbXVsU3pGcVpYTjNjWjdiUHdTT1J5cm9VZApBbEpuUnUxcHZBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  localhost.csr: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1V6Q0NBVHNDQVFBd0RqRU1NQW9HQTFVRUN3d0RTVUpOTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQwpBUThBTUlJQkNnS0NBUUVBd0g0bklnSGh2YjdBVUlIZC9WVW1laTFCejh3a1N0UmpxYVBVRjM1WldUQzIxQVhjCmN1MXM3ZmJhR1JJbGlKd21Kc3I2UDlEcUZIeWlySCsyVkFlWjZNM0h5VEVic3EzbnFMRkhYdWhzT2R2MURsdTkKeTZZMnRPL1owOGVTVXVsM3FOVG1iTEhNYThrZWprVVRyVmhkUVBWYS9Jay90YzRwaFE0VVMrSHplaVZVTUJXTQpuNUIyY0QwOVhlTkNJWnVrU0g5eTlqWlVTQTgwYmVUVWNQaElVUi9CTDR4eTJGRDVpQkhjaWpxOE1xVHVrNklrCjJUTUl2Z0xRQThWUFRUdXh5KzBOcGl6dlR3clpYUWw3MzM5YUFIMHJFU3ZvZ2lLVnFCWjdJbzJTcXRpTjFvcHkKcUZhYjRFMm1OaUx4U1VEamNMcjg1VjBIaXREeituazhTTVlWN3dJREFRQUJvQUF3RFFZSktvWklodmNOQVFFTApCUUFEZ2dFQkFDOTdtNUFyR1pFMjBCRTQzYUVGNnlDQlg4b1ZCNVZrbzhoSW81WWpSUmVOV2VPTUNRTDZzODZFCk1JajlYdjB5R3NoRk13VGtDNEd4aDhRTlhpdmpTUUJxL2Z6UVJmNGV1c3ZKRkY0YnFEamsxUHBSNWRrb0EvdlEKUWpoOHlCd05HaU5namg2Y1VGTWZVM2JBSnEyeE8yM3FvZThJY01halhQMjRzZG5ERm1aRzdtTHRMR1ZEYTlvQQorKzcwZEtNSlVRd3RGQWlNd1FMQXpKUVZ1SEcyblRJYjNzeDNSNEtqUTZJRUNvcHQ0N0ZoOUk2aVhURmM4N056CmRuNkVCS1ZsY0VjRC91enpaSkZIdnZHWUNIU0dMa0p3RnVLVStlZlM4VUw0aEZYYUd3cnlISVZtOGx6ZmZIWVgKUkw1RlEvUHVabmM4ODRyd1pGNjNnV2RGWFFrVitMST0KLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==
  localhost.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRREFmaWNpQWVHOXZzQlEKZ2QzOVZTWjZMVUhQekNSSzFHT3BvOVFYZmxsWk1MYlVCZHh5N1d6dDl0b1pFaVdJbkNZbXl2by8wT29VZktLcwpmN1pVQjVub3pjZkpNUnV5cmVlb3NVZGU2R3c1Mi9VT1c3M0xwamEwNzluVHg1SlM2WGVvMU9ac3NjeHJ5UjZPClJST3RXRjFBOVZyOGlUKzF6aW1GRGhSTDRmTjZKVlF3Rll5ZmtIWndQVDFkNDBJaG02UklmM0wyTmxSSUR6UnQKNU5SdytFaFJIOEV2akhMWVVQbUlFZHlLT3J3eXBPNlRvaVRaTXdpK0F0QUR4VTlOTzdITDdRMm1MTzlQQ3RsZApDWHZmZjFvQWZTc1JLK2lDSXBXb0Zuc2lqWktxMkkzV2luS29WcHZnVGFZMkl2RkpRT053dXZ6bFhRZUswUFA2CmVUeEl4aFh2QWdNQkFBRUNnZ0VBZnV1dlNkRUwwMXlPMllhSHBKNGNmTHFTaGowSVFQN0JwLzBKdjJQajdkY2MKOWJmWG56L0Ziekl3cEE4L0NGQk5KNDcyYWxXSnduQmJvbm1pOHMwQVFteE1xdS9pWDNJaktTdWE3NDA0cnYzRgpHdTZLdWxpaUFiT1VZUHRhRTZrMDZQRlg3WnRlT2tPbURoQ2w1TW82MHJYMGhFYks1MGxFUHlNRlp2Tlk0dFBOCloyc0tKdlFsNUZzNkxFSEZuVHgva20yYlRXelRKckpzWkZJaFBmOWNzcmFaUHdFUEZBQXczVzRET3JlU0R2emcKUFNpRkxXVjhTV2pPYzdQVk1aa3lsMFY5cjVrclB3aHJ3S0lVb2p4cU80U3NndGpROEl4UUF2TEpLaGZ6SHhTRgp5MWhIdXRRU0o0NDYvdi9VbzY1TWRlYlluWGFsRis3NlVINW9BeS9MWVFLQmdRRGcwNmsyaUFDbmVkenhydE02CnVNbGt3blpUbGRDZGZDMzJXci93OVN6eFh1aWcvQnZScXVqSTRCcTI1YURYbG1RRnBmeTdoYUw4a1QvMExJdVIKMTFWUmF4SjJNNjhJcHBadnpoa1ZzQVdRWGJ5dUl1MWRiOFVVTU80cWUxVXZTakRscGxlQ1hvcHRoT05vVTk0bgovaCtpblFSRWVKWGtReURQaGVqRGRSSXN3d0tCZ1FEYkxzZW4yK2NJVklTbjNtTFczQ1NGRHFxUGtJQnc1SW9LCjMyd0tzNWp4anIwdVBtdjQvaHlqZFlWWmZPcGpOWHhHbDBvUm9yNGc1SWFmR2h2bWJLVFVRU1dLTjhEZ1BDTWQKWGFseFJobXJXZW5XM1RLK1MvMCtwTnBIbnBCd2d2SmVhNEFtT210WlRHbVdPQzErZ2gwTzJUMUIvQ0JMZ0tHKwpzL2s3NUdrUFpRS0JnRGV3RmNTOUVUUnFlZkNmTmhEZ2Zubm50UGxsTFdRa3d4bTNScjIvYk45b2U4U01UYk8wCldxNk8yKzhibDZodXh0MmpUS09DS1duWDdIaGxwRGgrbHRKdzdBUzlMb2k5QXB3MDkzK290dWdZWDhqZU85OGQKOVRuWUdOWUs4SUdqSmROc1RWYXNaaXRVZENOK1NwT3JYVmlnL2RLYjc3eTNaK1FmTGhWajVSbVRBb0dCQU00QwpWQXBEdUF5dVU5anNQdjR2Lyt0SDg2dm9aN0MwUGNNbWFBaE84ZXZvKzRzaGhKNk5TU0doN2VwRWJKRSt6a1lUCklMMGV0NUYyK2NsRTR3QmJFVG1tMmIvbDAxVnZjSm5EVk9Wd3UrUEFLUGVaQkg2ME1aelZtWXhEVHdOUk1ManEKVlpLWXloa3VwdmRZYWZwRUZVZkZpN3dmVzhOYmJhc3V3WTAzakQrNUFvR0JBSXVNcDc0eUpBSTV5VEU5ZkNUUgo1S2FTOE9ONGVvblBOcGk4TlVQMlp0cENiME9MQ0pkUUdrQ1JqUmdYcUhwTHFzSE0zdEF6WjBWTEUvVlk0Z1hYCnU5WEdQcTd5ajVZQ25BTU5lT0x1Sk8zclc2bVZNUTREQVRQc0szc01LREpqZnRuWGZFbUJJTXgxTG84UUVkQ2YKeGpqZkRKUHozNE9zMmRleGI1dnphS2xuCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
---
apiVersion: v1
kind: Service
metadata:
  name: plugin-repo
  labels:
    app: plugin-repo
spec:
  ports:
  - name: client-connect
    port: 9443
    targetPort: 9443
  selector:
    app:  plugin-repo
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: plugin-repo
  labels:
    app: plugin-repo
spec:
  port:
    targetPort: client-connect
  to:
    kind: Service
    name: plugin-repo
    weight: 100
  tls:
    termination: passthrough
  wildcardPolicy: None
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ua-plugin-repo-pvc
  namespace: REPLACE_WITH_TARGET_NAMESPACE
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: plugin-repo
  labels:
    app: "plugin-repo"
    chart: "ibm-ua-operator"
    heritage: "Tiller"
    release: "kindred-lightningbug"
spec:
  replicas: 1
  serviceName: "plugin-repo"
  selector:
    matchLabels:
        app: "plugin-repo"
        chart: "ibm-ua-operator"
        heritage: "Tiller"
        release: "kindred-lightningbug"
        component: "operator"
  template:
    metadata:
      annotations:        
        productID: "9f22bc0647affc5cad4686c8853ec3a8"
        productName: "Unified Agent Plug-in Repo"
        productVersion: "2.3"
        productMetric: AUTHORIZED_USER
        cloudpakId: "e46b1bfe85b5ffac1e8eefadf22d988f"
        cloudpakName: "IBM Cloud Pak for Multicloud Management"
        cloudpakVersion: "2.3"
      labels:
        app: "plugin-repo"
        chart: "ibm-ua-operator"
        heritage: "Tiller"
        release: "kindred-lightningbug"
        component: "operator"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                  - amd64
                  - ppc64le
                  - s390x
      hostNetwork: false
      hostPID: false
      hostIPC: false
      securityContext:
        fsGroup: 1001
        runAsGroup: 1001
        runAsNonRoot: true
        runAsUser: 1001
      serviceAccountName: plugin-repo
      volumes:
      - name: pluginrepokey
        secret:
          defaultMode: 420
          secretName: plugin-repo-https-secret 
      - name: plugins-volume
        emptyDir: {}
      - name: plugin-repo
        persistentVolumeClaim:
          claimName: ua-plugin-repo-pvc
      initContainers:
        - name: pluginsimage
          image: REPLACE_WITH_YOUR_PLUGINS_IMAGE
          command: 
            - "/bin/bash"
            - "-c"
            - "cp -r /opt/plugins/*.*  /mnt/plugins"
          imagePullPolicy: Always
          resources:
            limits:
              memory: 512Mi 
              cpu: 500m 
            requests:
              memory: 200Mi
              cpu: 100m
          securityContext:
            capabilities:
              drop:
               - ALL
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
          volumeMounts:
          - name: plugins-volume
            mountPath: /mnt/plugins
      containers:
        - name: plugin-repo
          image: REPLACE_WITH_YOUR_REPO_IMAGE
          imagePullPolicy: Always
          resources:
            limits:
              memory: 512Mi 
              cpu: 500m 
            requests:
              memory: 200Mi
              cpu: 100m
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
            capabilities:
              drop:
               - ALL
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
          volumeMounts:
          - name: pluginrepokey  
            mountPath: /opt/ibm/keyfiles
          - name: plugins-volume
            mountPath: /opt/plugins
          - name: plugin-repo
            mountPath: /tmp/repo
          livenessProbe:
            exec:
              command:
                - cat
                - /opt/repo/seelog-repo.xml
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            exec:
              command:
                - cat
                - /opt/repo/run.sh
            initialDelaySeconds: 3
            periodSeconds: 3

